import networkx as nx
from auxilary_functions import bitpack_decode, bitpack_encode, plot_graph, draw_representatives, total_weight
import numpy as np
import time
import multiprocessing
import os
import subprocess
import sympy as sp
from itertools import combinations
import shutil


def call_generate_graphs(n,d, encoded_value,path,index):
    """
    Calls the C code to generate all non-isomorphic weighted graphs
    for a given graph structure and writes the bitpack encoded graphs
    to a single file based on the index.

    Args:
        n(int): Number of vertices
        d(int): Local dimension
        encoded_value(int): Bitpacked graph for the simple graph
        path(str): Path to the C file
        index(int): The index of the simple graph
    """

    result = subprocess.run([path, str(n), str(d), str(encoded_value)], capture_output=True, text=True) #Calls the C code
    output_dir = os.path.join(os.getcwd(),f"d{d}_c",str(n))
    graphs = {int(line) for line in result.stdout.splitlines()} #Parse the C output
    output_file = os.path.join(output_dir, f"{index}.txt")
    with open(output_file, "w") as f:
        for graph in graphs:
            f.write(str(graph) + "\n")

def generate_graphs_c(n,d, path, filename, num_workers=multiprocessing.cpu_count()):
    """
    Generates all the weighted non-isomorphic graphs for a given n and d.
    Uses multiprocessing.

    Args:
        n(int): Number of vertices
        d(int): Local dimension
        path(str): Path to the C file
        filename(str): Name or path to the file of non-isomorphic simple graphs generated by geng
        num_workers(int): Number of CPU threads to use. Uses all of them by default
    """

    with open(filename, "r") as file:
        graph6_lines = [line.strip() for line in file if line.strip()]
    iso_graphs = [bitpack_encode(nx.to_numpy_array(nx.from_graph6_bytes(line.encode()),dtype=int),d) for line in graph6_lines] #Read the non-isomorphic simple graphs and convert from graph6 to bitpack encoding
    ts=time.time()

    output_dir = os.path.join(os.getcwd(),f"d{d}_c",str(n))
    os.makedirs(output_dir, exist_ok=True)
    with multiprocessing.Pool(num_workers) as pool:
        index=0
        while iso_graphs:
            batch_size = min(len(iso_graphs), num_workers)
            batch = [iso_graphs.pop(0) for _ in range(batch_size)] #Create a batch
            print(f"{len(iso_graphs)}:{time.time()-ts}")
            pool.starmap(call_generate_graphs, [(n, d, g, path,index*num_workers+batch.index(g),ts) for g in batch]) #Run call_generate_graphs in parallel for the graphs in batch
            index+=1
    


def call_complementation_layer(n, d, encoded_value,path):
    """
    Calls the C code that scales and complements a single layer.
    Returns a set of the minimal isomorphic graph encodings.

    Args:
        n(int): Number of vertices
        d(int): Local dimension
        encoded_value(int): Bitpacked graph
        path(str): Path to the C file
    """
    result = subprocess.run([path, str(n), str(d), str(encoded_value)], capture_output=True, text=True) #Calls the C file
    return {int(line) for line in result.stdout.splitlines()}


def orbit_atlas_c(path,n,d, num_workers=multiprocessing.cpu_count()):
    """
    Creates an atlas of local scalings and local complementatinos for
    all the graphs of local dimension d and number of vertices n.
    
    Args:
        path(str): Path to the C file
        n(int): Number of vertices
        d(int): Local dimension
        num_workers(int): Number of CPU threads to use. Uses all of them by default
    """
    graphs=set()
    ts=time.time()
    directory=os.path.join(os.getcwd(), f"d{d}_c", str(n))
    for filename in os.listdir(directory):
        file_path = os.path.join(directory, filename)

        
        if os.path.isfile(file_path):
            with open(file_path, "r") as file:
                for line in file:
                    graph = int(line.strip()) 
                    graphs.add(graph)
    G=nx.Graph()
    G.add_nodes_from(graphs) #Initialize the atlas graph with all the graphs as vertices.

    with multiprocessing.Pool(num_workers) as pool:
        while graphs:
            batch_size = min(len(graphs), num_workers)
            batch = [graphs.pop() for _ in range(batch_size)] #Create a batch
            print(f"{len(graphs)}:{time.time()-ts}")
            complements = pool.starmap(call_complementation_layer, [(n, d, g, path) for g in batch]) #Run call_complementation_layer in parallel for the graphs in batch
            for i in range(batch_size):
                for complement in complements[i]:
                    G.add_edge(batch[i],complement) #Add the edges obtained from local scaling and local complementing
    return G


def separate_orbits(G):
    """
    Separates the atlas into orbits.

    Args:
        G(nx.Graph): Atlas graph
    """
    components = list(nx.connected_components(G)) #Separates disjoint parts of the atlas
    subgraphs = [G.subgraph(nodes).copy() for nodes in components]
    return subgraphs

def find_representatives(n,d):
    represenatives=[]
    for i in range(3,n+1):
        directory=f"orbits_d{d}_n{i}_separated_sorted"
        for j in range(len(os.listdir(directory))):
            file_path=os.path.join(directory,f"orbit_{j}")
            G=nx.read_edgelist(file_path,data=False)
            graphs=list(G.nodes)
            represenatives.append([int(min(graphs,key=lambda x: (int(x).bit_count(), total_weight(int(x)),x))),(i,j)])
    return represenatives
            


def call_measure(n,d,directory,i,strategy):
    """
    Calculates the schmidt measure for orbit i.
    
    Args:
        n(int): Number of vertices
        d(int): Local dimension
        directory(str): Directory of orbit files
        i(int): Index of the orbit
        strategy(str): Coloring strategy for greedy_color
    """

    current_measure=0
    orbit=nx.read_edgelist(directory+f"/orbit_{i}", data=False) #Import orbit
    exists_two_colorable=False
    for g in orbit.nodes: #Check if there is a two colorable graph in the orbit
        adj_matrix=bitpack_decode(int(g),n,d)
        nx_g=nx.from_numpy_array(adj_matrix)
        coloring = nx.coloring.greedy_color(nx_g, strategy=strategy)
        if max(coloring.values())==1:
            exists_two_colorable=True
            break
    max_max_rank=0 #Maximum rank found in the whole orbit
    found=False
    for g in orbit.nodes: #Try to calculate the Schmidt measure for the orbit and if an exact value is found break
        result=calculate_schmidt_measure(g,exists_two_colorable, max_max_rank,n,d, strategy)
        if type(result[1])==int:
            max_max_rank=result[1]
        if result[2]==True:
            current_measure=result[0]
            if type(result[1])==bool:
                found=True
                break
    if type(current_measure) == int and current_measure==0:
        current_measure=[0,0]
    if found==False: #Perform a breadth first check by removing a vertex and using the resultant graph for bounds
        temp_graphs=list(orbit.nodes)
        for j in range(1,n-2): 
            graphs=temp_graphs.copy()
            temp_graphs=[]
            for g in graphs:
                adj_matrix=bitpack_decode(int(g),n-j+1,d)
                nx_g=nx.from_numpy_array(adj_matrix)
                for v in nx_g.nodes:
                    temp_nx_g=nx_g.copy()
                    temp_nx_g.remove_node(v)
                    if nx.is_connected(temp_nx_g):
                        temp_graphs.append(bitpack_encode(nx.to_numpy_array(temp_nx_g,dtype=int),d))
                        mapping = dict(zip(temp_nx_g, range(n-j)))
                        temp_nx_g=nx.relabel_nodes(temp_nx_g, mapping)
                        result=sub_calculate_schmidt_measure(temp_nx_g,n-j,d, strategy)
                        if result !=0 and (current_measure[1]==0 or result+j<current_measure[1]):
                            current_measure[1]=result+j
                        if result !=0 and (result>current_measure[0]):
                            current_measure[0]=result
                        if result !=0 and current_measure[0]==current_measure[1]:
                            break
                if current_measure[0]==current_measure[1]:
                    break
            if current_measure[1]!=0 and current_measure[0]==current_measure[1]:
                current_measure=current_measure[1]
                found = True
                break
        print(f"{i}:{current_measure}:Color")
    if found == False: #If still no exact value found try to check all bipartitions
        for g in orbit.nodes:
            adj_matrix=bitpack_decode(int(g),n,d)
            nx_g=nx.from_numpy_array(adj_matrix)
            result =  all_bipartitions_measure(adj_matrix,n,d)
            if result != 0  and result > current_measure[0]:
                current_measure[0]=result
        print(f"{i}:{current_measure}")
    else:
        print(f"{i}:{current_measure}:Early")
    return current_measure


def all_bipartitions_measure(adj_matrix,n,d):
    """
    Calculates the lower bound based on all possible bipartitions
    
    Args:
        adj_matrix(np.array): Adjacency matrix of the graph
        n(int): Number of vertices
        d(int): Local dimension
    """

    nx_g=nx.from_numpy_array(adj_matrix)
    max_rank=0
    for i in range(1, n // 2 + 1):
        for subset in combinations(list(nx_g.nodes), i):
            submatrix=adj_matrix[np.ix_(sorted(subset),sorted(set(nx_g.nodes)-set(subset)))]
            rank = rank_over_finite_field(submatrix,d)
            if rank>max_rank:
                max_rank=rank
    return max_rank



def orbit_schmidt_measure(n,d, strategy):
    """
    Calculates the Schmidt measures of all the orbits,
    for a given n and d.

    Args:
        n(int): Number of vertices
        d(int): Local dimension
        strategy(str): Networkx coloring strategy
    """
    directory=f"orbits_d{d}_n{n}_separated_sorted"
    num_orbits=len(list(os.listdir(directory)))
    schmidt_measures=[]
    num_workers = multiprocessing.cpu_count()
    orbits=list(range(num_orbits))
    with multiprocessing.Pool(num_workers) as pool:
        while orbits:
            batch_size = min(len(orbits), num_workers)
            batch = [orbits.pop(0) for _ in range(batch_size)] #Create a batch
            schmidt_measures.extend(pool.starmap(call_measure, [(n, d, directory, i, strategy) for i in batch])) #Run call_measure in parrallel
            print(len(orbits))                
    return schmidt_measures


def sub_calculate_schmidt_measure(nx_g,n,d, strategy):
    """
    Subroutine for the breadth first Schmidt measure calculation
    
    Args:
        nx_g(nx.Graph): Graph in networkx format
        n(int): Number of vertices
        d(int): Local dimension
        strategy(str): Coloring strategy for greedy_color
    """
    adj_matrix=nx.to_numpy_array(nx_g,dtype=int)
    coloring = nx.coloring.greedy_color(nx_g, strategy=strategy)
    color_classes = {c: [v for v in coloring if coloring[v] == c] for c in set(coloring.values())}
    if max(coloring.values()) == 1 and rank_over_finite_field(adj_matrix,d)==n: #Exact value for full rank
        return n//2
        
    elif max(coloring.values()) == 1: #In case of two colorable
        max_rank = 0
        colors=list(color_classes.keys())
        min1=10
        for k in range(len(colors)):
            A = color_classes[colors[k]]  # One part of the bipartition
            if len(A)<min1:
                min1=len(A)
            B = [v for j in range(len(colors)) if j != k for v in color_classes[colors[j]]]  # Other part
            submatrix=adj_matrix[np.ix_(A, B)]
            rank = rank_over_finite_field(submatrix,d)
            max_rank = max(max_rank, rank)
        if max_rank==min1:
            return max_rank
        elif max_rank==n//2:
            return max_rank
    elif max(coloring.values()) == 2: #In case of three colorable
        max_rank = 0
        colors=list(color_classes.keys())
        min1=10
        min2=10
        for k in range(len(colors)):
            A = color_classes[colors[k]]  # One part of the bipartition
            if len(A)<min1:
                min1=len(A)
            elif len(A)<min2:
                min2=len(A)
            B = [v for j in range(len(colors)) if j != k for v in color_classes[colors[j]]]  # Other part
            submatrix=adj_matrix[np.ix_(A, B)]
            rank = rank_over_finite_field(submatrix,d)
            max_rank = max(max_rank, rank)
        if max_rank==min1+min2:
            return max_rank
    elif max(coloring.values()) == 1:
        return n//2
    return 0

def calculate_schmidt_measure(g, exists_two_colorable, max_max_rank,n,d, strategy):
    """
    Tries to calculate the Schmidt measure based on two and three colorability.

    Args:
        g(int): Encoded graph
        exists_two_colorable(bool): Existence of a two colorable in the orbit
        max_max_rank(int): Maximum rank found in the orbit
        n(int): Number of vertices
        d(int): Local dimension
        strategy(str): Networkx coloring strategy
    """
    adj_matrix=bitpack_decode(int(g),n,d)
    nx_g=nx.from_numpy_array(adj_matrix)
    coloring = nx.coloring.greedy_color(nx_g, strategy=strategy)
    color_classes = {c: [v for v in coloring if coloring[v] == c] for c in set(coloring.values())}
    if max(coloring.values()) == 1 and rank_over_finite_field(adj_matrix,d)==n: #If the matrix is full rank and it is two colorable, returns the exact value
        return n//2, True, True
        
    elif max(coloring.values()) == 1: #If it's two colorable but not full rank
        max_rank = 0
        colors=list(color_classes.keys())
        min1=10
        for k in range(len(colors)): #Check color bipartitions
            A = color_classes[colors[k]]  # One part of the bipartition
            if len(A)<min1:
                min1=len(A)
            B = [v for j in range(len(colors)) if j != k for v in color_classes[colors[j]]]  # Other part
            submatrix=adj_matrix[np.ix_(A, B)]
            rank = rank_over_finite_field(submatrix,d)
            max_rank = max(max_rank, rank)
        if max_rank==min1:
            return max_rank, True, True
        elif max_rank==n//2:
            return max_rank, True, True
        elif  max_max_rank<=max_rank:
            max_max_rank=max_rank
            
            
            return [max_rank,n//2], max_max_rank, True
    elif max(coloring.values()) == 2: #If three colorable
        max_rank = 0
        colors=list(color_classes.keys())
        min1=10
        min2=10
        for k in range(len(colors)):
            A = color_classes[colors[k]]  # One part of the bipartition
            if len(A)<min1:
                min1=len(A)
            elif len(A)<min2:
                min2=len(A)
            B = [v for j in range(len(colors)) if j != k for v in color_classes[colors[j]]]  # Other part
            submatrix=adj_matrix[np.ix_(A, B)]
            rank = rank_over_finite_field(submatrix,d)
            max_rank = max(max_rank, rank)
        if max_rank==min1+min2: #Exact value found
            return max_rank, True, True

        elif max_max_rank<max_rank:
            max_max_rank=max_rank
            if exists_two_colorable: 
                return [max_rank,n//2], max_max_rank, True #If a two colorable exists then the upper bound is given
            else:
                return [max_rank,0], max_max_rank, True #No upper bound found
    return 0, False, False
    
def mod_inv(a, d):
    """Compute modular inverse of a mod d (assuming d is prime)."""
    return pow(a, -1, d)

def rank_over_finite_field(matrix, d):
    """Compute the rank of a matrix over the finite field F_d."""
    mat = sp.Matrix(matrix).applyfunc(lambda x: x % d)  # Reduce elements mod d
    rref_matrix, pivot_cols = mat.rref(iszerofunc=lambda x: x % d == 0)
    return len(pivot_cols)


def orbit_value(orbit,directory):
    """
    Returns the number of edges, total weight and encoding of
    the representative of the orbit
    
    Args:
        orbit(string): Orbit number
        directory(string): Path to orbit files
    """
    nodes=nx.read_edgelist(os.path.join(directory,orbit)).nodes
    rep=int(min(nodes,key=lambda x: (int(x).bit_count(), total_weight(int(x)),x)))
    return (int(rep).bit_count(), total_weight(int(rep)),int(rep))


def sort_orbits(d):
    for n in range(3,8):
        directory=f"orbits_d{d}_n{n}_separated"
        sorted_orbits=sorted(os.listdir(directory),key= lambda o: orbit_value(o,directory))
        new_directory=f"orbits_d{d}_n{n}_separated_sorted"
        os.makedirs(new_directory, exist_ok=False)
        for new_index, original_filename in enumerate(sorted_orbits):
            src_path = os.path.join(directory, original_filename)
            dst_filename = f'orbit_{new_index}'
            dst_path = os.path.join(new_directory, dst_filename)
            shutil.copy2(src_path, dst_path)